Insert title functionality
lblod/ember-rdfa-editor-besluit-plugin pull request #2
Opened 2022-01-18 15:22 UTC by lagartoverde

2022-01-26 10:24 UTC, nvdk requested changes
I think it would be better if the buttons are listed below each other tbh.

2022-01-26 10:26 UTC, lagartoverde commented
mmmm, they should be in 2 separate lines, they are not? I will take a look in some time

2022-01-27 09:54 UTC, lagartoverde commented
My bad, I changed the order last minute and I didn't realize the layout was not correct anymore, it should be good now :)

2022-01-27 11:10 UTC, nvdk approved these changes

2022-01-27 11:10 UTC, merged